# Global settings
DATASET_DIR = '../dataset/'
TRAIN_DIR = DATASET_DIR + '/Training/'
TEST_DIR = DATASET_DIR + '/Testing/'
CLASS_COUNT = 4
IMAGE_WIDTH = 128
IMAGE_HEIGHT = 128
CHANNELS = 3
IMAGE_SIZE = (IMAGE_WIDTH, IMAGE_HEIGHT)
IMAGE_SHAPE = (IMAGE_WIDTH, IMAGE_HEIGHT, CHANNELS)
BATCH_SIZE = 32
